# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oh2YRNl-65GgiBob1I4s-qs_nAywvbOD
"""

# Dataset: [Programming Language, CGPA, Internship, Placement]
data = [
    ['Python', 'High', 'Internship', 'Yes'],
    ['Python', 'High', 'No Internship', 'Yes'],
    ['Java', 'Low', 'Internship', 'No'],
    ['Python', 'High', 'Internship', 'Yes']
]

S = ['0'] * (len(data[0]) - 1)
G = ['?'] * (len(data[0]) - 1)

for row in data:
    x, y = row[:-1], row[-1]

    if y == 'Yes':
        if S[0] == '0':
            S = x.copy()
        else:
            for i in range(len(S)):
                if S[i] != x[i]:
                    S[i] = '?'
    else:
        for i in range(len(S)):
            if S[i] != '?' and S[i] != x[i]:
                G[i] = S[i]
